### ISSUE TITLE
Why not CBOR?

### ISSUE THREAD

**Issue by martinheidegger** [Path-Check/paper-cred#10]
A common way for me to encode data is using binary formats and encode them using [base 32](https://en.wikipedia.org/wiki/Base32#Crockford's_Base32) and while I usually use msgpack or protocol-buffers, in this case I believe that [CBOR](https://en.wikipedia.org/wiki/CBOR) may be a better format for the case at hand. They should reduce the amount of strings a bit, resulting in shorter URLs (better codes). (One thing that comes to mind: a int64 encoded timestamp is 2 characters and should last for a while)

**Comment by vitorpamplona** [comment]
Well, technically, the best way is not representing the information in name-value pairs at all, like a CSV row. That might be necessary for the certificate over SMS part. @justindossey actually explored that idea in the Badge. 

We might do a version with a URI format, a JSON format, and a delimiter-separated format to help.

**Comment by martinheidegger** [comment]
naturally: replacing the names with locations is a good idea. CBOR does support arrays as items and is just generally quite resource saving.
