### ISSUE TITLE
Geolocation instead of area/city

### ISSUE THREAD

**Issue by martinheidegger** [Path-Check/paper-cred#11]
An area can easily be mistaken for a nearby area by human mistake or ambiguity for the administrator or developer installing this system at a location. If the location of the vaccination site was specified as geolocation it would solve several issues: The encoding of city names, the ambiguity for the implementer, and it would result in less data to be encoded.
There are reverse geolocation lookups that turn a given geolocation into an area.

**Comment by vitorpamplona** [comment]
The location in the coupon is not a reference to where the issuer is. But what is the scope of the coupon itself. In the demo, the coupon is for Boston residents, for instance. 

We don't store the location of the service (it's just not relevant to the vaccination journey).

**Comment by martinheidegger** [comment]
Locations like "Springfield" or "Athens" - In my area "Sumiyoshi" are more than ambiguous that may be understood by some people differently. If it is just a index in a local lookup (that does not need to be globally known: Why not replace it with a simple small-int? What can providers gain as value from the area?
