### ISSUE TITLE
Thermal Printers as first-class citizen

### ISSUE THREAD

**Issue by martinheidegger** [Path-Check/paper-cred#12]
Thermal printers are _very_ fast and cheap which allows quick processing in many environments. There are [plugins](https://parzibyte.github.io/plugin-ticket-js/en/) for browsers that allow to print directly using webbrowsers. Would it be reasonable to mention that the codes need to be printable through common thermal printers?

**Comment by vitorpamplona** [comment]
Agree. We are in fact using battery-powered Bluetooth-enabled ones that connect straight to the phone of the vaccinator. No cables or even WI-FI routers are required. 

But it's also fair to say that the protocol should not require any specific printer. In the end, people can print them in regular A4 HP printers or ask a local Printing company to do for them.

**Comment by martinheidegger** [comment]
Almost everything that can be printed on thermal printers can also be printed on A4/Letter, I am not sure the other way works.

**Comment by vitorpamplona** [comment]
We can probably derive a maximum DPI for the QR Code generation in such a way that fits most printers.
