### ISSUE TITLE
DNS TXT record

### ISSUE THREAD

**Issue by DenisPitcher** [Path-Check/paper-cred#30]
The readme suggests conversion of the PEM to remove the comments and new line characters however the javascript sample app doesn't recognize this format and the current text record for keys.pathcheck.org doesn't either:
`"-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6DeIun4EgMBLUmbtjQw7DilMJ82YIvOR\n2jz/IK0R/F7/zXY1z+gqvFXfDcJqR5clbAYlO9lHmvb4lsPLZHjugQ==\n-----END PUBLIC KEY-----\n"`

**Comment by vitorpamplona** [comment]
Hi Denis, 

Yes, we made the change on the protocol and the demo app did not follow. We are currently finishing this adjustment on the demo codebase.

**Comment by vitorpamplona** [comment]
I also quickly updated the Javascript, Ruby, Python, Java and Sell Script demos. You can test with pcf.vitorpamplona.com while keys.pathcheck.org doesn't update.

**Comment by vitorpamplona** [comment]
keys.pathcheck.org has been updated as well.

**Comment by DenisPitcher** [comment]
Thanks, though it looks like you're still not including the specified \\n in keys.pathcheck.com and pcf.vitorpamplona.com

**Comment by vitorpamplona** [comment]
Hum.. which one are you referring to? The only `\n` that should be converted is the one in the middle of the public key. It should be turned into a `\\n`. You can see it down below. 

```MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6DeIun4EgMBLUmbtjQw7DilMJ82YIvOR\\n2jz/IK0R/F7/zXY1z+gqvFXfDcJqR5clbAYlO9lHmvb4lsPLZHjugQ==```

**Comment by DenisPitcher** [comment]
Hi Vitor,

Sorry, I should have written \\n.  For keys.pathcheck.org I'm seeing 
`MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6DeIun4EgMBLUmbtjQw7DilMJ82YIvOR\n2jz/IK0R/F7/zXY1z+gqvFXfDcJqR5clbAYlO9lHmvb4lsPLZHjugQ==`
when using nslookup and when using https://mxtoolbox.com/SuperTool.aspx?action=txt%3akeys.pathcheck.org&run=toolpage but when using the google https://dns.google/resolve?name=KEYS.PATHCHECK.ORG&type=TXT
`MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6DeIun4EgMBLUmbtjQw7DilMJ82YIvOR\\n2jz/IK0R/F7/zXY1z+gqvFXfDcJqR5clbAYlO9lHmvb4lsPLZHjugQ==`

So I'm unclear as to whether I specifically need to replace "\n" with "\\n" as specified in my txt record or not

**Comment by vitorpamplona** [comment]
Some DNS Lookup tools already convert the \\n to \n for you. It depends on the lib you use. If they do, then you should not need to convert yourself.
