### ISSUE TITLE
3rd Dose for EU Green Pass Generator

### ISSUE THREAD

**Issue by Dean-xXx** [Path-Check/paper-cred#33]
Hi, are you going to add the option for 3rd Dose on the EU Green Pass generator?

Appreciate it.

**Comment by vitorpamplona** [comment]
For the demo website? I am not sure. It doesn't seem that important.

**Comment by Dean-xXx** [comment]
For this one: https://github.pathcheck.org/eu.dgc.html

Would be nice to be updated with the current situation with the booster vaccines.

**Comment by vitorpamplona** [comment]
Yep, that's the demo website. I don't think there is a need to expand it. Once one does 2 vaccines, it's straightforward to do 3

**Comment by Dean-xXx** [comment]
Ah, that’s cool!
Would be great to see that done when possible.

Thanks for quick replies @vitorpamplona

**Comment by mbirth** [comment]
Just for the record: When I got my QR code for the booster vaccination, I actually got 3 QR codes as they re-coded every single vaccination again.

So I now have these QR codes:

* vaccination 1/2 - Biontech Comirnaty
* vaccination 2/2 - Biontech Comirnaty
* vaccination 3/3 - Moderna Spikevax

Only the last one is needed as it proves I've got 3 vaccinations.
